_SPR0_Y          DB
_SPR0_X          DB
_SPR0_NUM        DB
_SPR0_ATT        DB

_SPR1_Y          DB
_SPR1_X          DB
_SPR1_NUM        DB
_SPR1_ATT        DB

_SPR2_Y          DB
_SPR2_X          DB
_SPR2_NUM        DB
_SPR2_ATT        DB

_SPR3_Y          DB
_SPR3_X          DB
_SPR3_NUM        DB
_SPR3_ATT        DB

_SPR4_Y          DB
_SPR4_X          DB
_SPR4_NUM        DB
_SPR4_ATT        DB

_SPR5_Y          DB
_SPR5_X          DB
_SPR5_NUM        DB
_SPR5_ATT        DB

_SPR6_Y          DB
_SPR6_X          DB
_SPR6_NUM        DB
_SPR6_ATT        DB

_SPR7_Y          DB
_SPR7_X          DB
_SPR7_NUM        DB
_SPR7_ATT        DB

_SPR8_Y          DB
_SPR8_X          DB
_SPR8_NUM        DB
_SPR8_ATT        DB

_SPR9_Y          DB
_SPR9_X          DB
_SPR9_NUM        DB
_SPR9_ATT        DB

_SPR10_Y          DB
_SPR10_X          DB
_SPR10_NUM        DB
_SPR10_ATT        DB

_SPR11_Y          DB
_SPR11_X          DB
_SPR11_NUM        DB
_SPR11_ATT        DB

_SPR12_Y          DB
_SPR12_X          DB
_SPR12_NUM        DB
_SPR12_ATT        DB

_SPR13_Y          DB
_SPR13_X          DB
_SPR13_NUM        DB
_SPR13_ATT        DB

_SPR14_Y          DB
_SPR14_X          DB
_SPR14_NUM        DB
_SPR14_ATT        DB

_SPR15_Y          DB
_SPR15_X          DB
_SPR15_NUM        DB
_SPR15_ATT        DB

_SPR16_Y          DB
_SPR16_X          DB
_SPR16_NUM        DB
_SPR16_ATT        DB

_SPR17_Y          DB
_SPR17_X          DB
_SPR17_NUM        DB
_SPR17_ATT        DB

_SPR18_Y          DB
_SPR18_X          DB
_SPR18_NUM        DB
_SPR18_ATT        DB

_SPR19_Y          DB
_SPR19_X          DB
_SPR19_NUM        DB
_SPR19_ATT        DB

