_SPR0_Y     EQU     _OAMRAM 		; sprite Y 0 is the beginning of the sprite mem
_SPR0_X     EQU     _OAMRAM + 1
_SPR0_NUM   EQU     _OAMRAM + 2
_SPR0_ATT   EQU     _OAMRAM + 3

_SPR1_Y     EQU     _OAMRAM + 4
_SPR1_X     EQU     _OAMRAM + 5
_SPR1_NUM   EQU     _OAMRAM + 6
_SPR1_ATT   EQU     _OAMRAM + 7

_SPR2_Y     EQU     _OAMRAM + 8
_SPR2_X     EQU     _OAMRAM + 9
_SPR2_NUM   EQU     _OAMRAM + 10
_SPR2_ATT   EQU     _OAMRAM + 11

_SPR3_Y     EQU     _OAMRAM + 12
_SPR3_X     EQU     _OAMRAM + 13
_SPR3_NUM   EQU     _OAMRAM + 14
_SPR3_ATT   EQU     _OAMRAM + 15

