_SPR0_Y          DB
_SPR0_X          DB
_SPR0_NUM        DB
_SPR0_ATT        DB

_SPR1_Y          DB
_SPR1_X          DB
_SPR1_NUM        DB
_SPR1_ATT        DB

_SPR2_Y          DB
_SPR2_X          DB
_SPR2_NUM        DB
_SPR2_ATT        DB

_SPR3_Y          DB
_SPR3_X          DB
_SPR3_NUM        DB
_SPR3_ATT        DB

_SPR4_Y          DB
_SPR4_X          DB
_SPR4_NUM        DB
_SPR4_ATT        DB

