SCREEN_WIDTH       EQU     160
FIRST_COLUMN       EQU     8
FIRST_LINE         EQU     16
LAST_COLUMN        EQU     SCREEN_WIDTH + FIRST_COLUMN

BALL_WIDTH         EQU     8
BALL_HEIGHT        EQU     8

PADDLE_Y           EQU     144
PADDLE_WIDTH       EQU     3 * 8
