SCREEN_WIDTH       EQU     160
SCREEN_HEIGHT      EQU     144
FIRST_COLUMN       EQU     8
FIRST_LINE         EQU     16
LAST_COLUMN        EQU     SCREEN_WIDTH + FIRST_COLUMN
LAST_LINE          EQU     SCREEN_HEIGHT + FIRST_LINE

BALL_WIDTH         EQU     8
BALL_HEIGHT        EQU     8

PADDLE_Y           EQU     136
PADDLE_WIDTH       EQU     3 * 8

ITEM_WIDTH         EQU     8
ITEM_HEIGHT        EQU     8

FRAMES_ITEM_DEATH_ANIMATION     EQU     40      ; 40: alive, 39-1: animation for death, 0: dead


TILE_HEART				EQU		11
TILE_PACMAN_GHOST		EQU		12
TILE_DIAMOND			EQU		13
TILE_MUSHROOM			EQU		14